---
- name: Install Apache
  yum:
    name: httpd
    state: present
  become: yes

- name: Ensure Apache is started and enabled
  service:
    name: httpd
    state: started
    enabled: true
  become: yes
