# Vagrantfile_Carrydan
ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
Vagrant.configure("2") do |config|

  # Общие настройки для всех виртуальных машин
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  # Define the server machine
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "public_network", ip: "192.168.56.101", bridge: "ens33"

    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end

    # Provisioning script for the server
    server.vm.provision "shell", path: "server_provision.sh"
  end

  # Define the client machine
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "public_network", ip: "192.168.56.102", bridge: "ens33"

    client.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
    
    # Provisioning script for the client
    client.vm.provision "shell", path: "client_provision.sh"
    client.vm.synced_folder ".", "/vagrant"
    client.ssh.insert_key = false
  end

end