---
- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: true
  become: yes

- name: Ensure MySQL is started and enabled
  service:
    name: mysql
    state: started
    enabled: true
  become: yes
